### ISSUE TITLE
Cannot read property 'shortUrl' of undefined

### ISSUE THREAD

**Issue by ktkd** [GezimSejdiu/Rocket.Chat-Trello-Integration#1]
Hello, when i add your js in integration have this issue, looks like i should define shortUrl.
> rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error   TypeError: Cannot read property 'shortUrl' of undefined       at Script.process_incoming_request (script.js:1:420)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInNewContext (vm.js:18:15)       at Object.exports.runInNewContext (vm.js:49:17)       at Object.executeIntegrationRest [as action] (/app/bundle/programs/server/packages/rocketchat_integrations.js:2789:20)       at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:361:32)       at /app/bundle/programs/server/packages/nimble_restivus.js:250:33       at packages/simple_json-routes.js:98:9 
> [34mI20171113-09:29:32.921(0)

**Comment by GezimSejdiu** [comment]
Hi @ktkd ,
Not sure what is the error you are facing. The shortUrl variable comes from Trello API and it is used there in the script.  I just tested by today the same script and it is working (see the image below).

![testtrello](https://user-images.githubusercontent.com/5259296/32719145-a3b76aa6-c85f-11e7-839e-5c8d91ea3cee.png)
Could you please let me know which version or Rocket.Chat you are using (i.e ours is at 0.59.3 - latest version).
Best regards,

**Comment by ktkd** [comment]
i have  0.59.3

here is part from rocketchat log, maybe you can  understand this issue -

`[34mI20171113-09:16:23.468(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error [Stack:] 
[34mI20171113-09:16:23.474(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error   TypeError: Cannot read property 'shortUrl' of undefined       at Script.process_incoming_request (script.js:1:420)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInNewContext (vm.js:18:15)       at Object.exports.runInNewContext (vm.js:49:17)       at Object.executeIntegrationRest [as action] (/app/bundle/programs/server/packages/rocketchat_integrations.js:2789:20)       at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:361:32)       at /app/bundle/programs/server/packages/nimble_restivus.js:250:33       at packages/simple_json-routes.js:98:9 
[34mI20171113-09:24:38.399(0)  
[34mI20171113-09:24:38.406(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error [Error running Script in Trigger Trello :] 
[34mI20171113-09:24:38.410(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error   function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}var Script=function(){function Script(){_classCallCheck(this,Script)}Script.prototype.process_incoming_request=function process_incoming_request(_ref){var request=_ref.request;console.log(request.content);var attachment_text="";var title_text="";var url=request.content.model.shortUrl;var author_name=request.content.action.memberCreator.fullName;var card_name=request.content.action.data.card.name;var card_link=request.content.action.data.card.shortLink;var board_link=request.content.action.data.board.shortLink;var board_name=request.content.action.data.board.name;var user_avatar="https://trello-avatars.s3.amazonaws.com/"+request.content.action.memberCreator.avatarHash+"/170.png";var message_text=author_name;if(request.content.model.name=="Exergo")return"";if(request.content.action.type=="updateCheckItemStateOnCard"||request.content.action.type=="deleteCheckItem"||request.content.action.type=="createCheckItem"){if(request.content.action.type=="updateCheckItemStateOnCard"){if(request.content.action.data.checkItem.state=="incomplete")message_text+=" unchecked ";else message_text+=" checked ";message_text+=" a checklist item<br>"}else if(request.content.action.type=="deleteCheckItem"){message_text+=" deleted a checklist item"}else if(request.content.action.type=="createCheckItem"){message_text+=" created a checklist item"}title_text=card_name;attachment_text="<br>Item: "+request.content.action.data.checkItem.name;attachment_text+="<br>Checklist: "+request.content.action.data.checklist.name;attachment_text+="<br>Card: "+card_name}else if(request.content.action.type=="addChecklistToCard"){message_text+=" added a checklist to card";title_text=card_name;attachment_text+="<br>Checklist: "+request.content.action.data.checklist.name;attachment_text+="<br>Card: "+card_name}else if(request.content.action.type=="removeChecklistFromCard"){message_text+=" removed a checklist from card";title_text=card_name;attachment_text+="<br>Checklist: "+request.content.action.data.checklist.name;attachment_text+="<br>Card: "+card_name}else if(request.content.action.type=="createCard"){var list_name=request.content.action.data.list.name;message_text=" New card ["+card_name+"](https://trello.com/c/"+card_link+") added to list ["+list_name+"](https://trello.com/b/"+board_link+")";url="https://trello.com/c/"+request.content.action.data.card.shortLink;title_text=card_name}else if(request.content.action.type=="deleteCard"){var list_name=request.content.action.data.list.name;message_text="Card [#"+request.content.action.data.card.idShort+"](https://trello.com/c/"+card_link+") deleted from list ["+list_name+"](https://trello.com/b/"+board_link+")";url="https://trello.com/c/"+request.content.action.data.card.shortLink;title_text=""}else if(request.content.action.type=="updateCard"){var data=request.content.action.data;if(data.listBefore){message_text="Card moved: \"["+card_name+"](https://trello.com/c/"+card_link+")\" from list \""+data.listBefore.name+"' to '"+data.listAfter.name+"'"}else if(data.old.name){var card_old_name=data.old.name;message_text="Card renamed from \""+card_old_name+"\" to \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(data.old.desc!=data.card.desc){var card_desc=data.card.desc;var old_desc=data.old.desc;if(old_desc!=""){card_desc="from \""+old_desc+"\" to \""+card_desc+"\""}message_text="Card updated: \"["+card_name+"](https://trello.com/c/"+card_link+")\"<br>**Description**: "+card_desc+""}else if(data.card.due!=data.old.due){var card_due=data.card.due;var due_action=card_due;if(due_action==null)due_action="Removed";message_text="Card updated: \"["+card_name+"](https://trello.com/c/"+card_link+")\"<br>**Due Date**: "+due_action+""}else if(data.card.closed==true){message_text="Card archived: \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(data.card.closed==false){message_text="Card unarchived: \"["+card_name+"](https://trello.com/c/"+card_link+")\""}}else if(request.content.action.type=="commentCard"){var data=request.content.action.data;message_text="**New comment on card \"["+card_name+"](https://trello.com/c/"+card_link+")\" by "+author_name+"**";attachment_text+="-----------------------------------------------------------<br>"+data.text}else if(request.content.action.type=="moveCardFromBoard"){var data=request.content.action.data;var board_target_name=data.boardTarget.name;message_text="Card moved: \"["+card_name+"](https://trello.com/c/"+card_link+")\" moved from \"["+board_name+"](https://trello.com/b/"+board_link+") to board \""+board_target_name+"\""}else if(request.content.action.type=="moveCardToBoard"){var data=request.content.action.data;var board_source_name=data.boardSource.name;message_text="Card moved: \"["+card_name+"](https://trello.com/c/"+card_link+")\" moved to \"["+board_name+"](https://trello.com/b/"+board_link+") from board  \""+board_source_name+"\""}else if(request.content.action.type=="addMemberToCard"){var data=request.content.action.data;var member=request.content.action.member.fullName;var member_url=request.content.action.member.username;message_text="New member ["+member+"](https://trello.com/"+member_url+") added to card \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(request.content.action.type=="removeMemberFromCard"){var data=request.content.action.data;var member=request.content.action.member.fullName;var member_url=request.content.action.member.username;message_text="Member ["+member+"](https://trello.com/"+member_url+") is removed from card \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(request.content.action.type=="addAttachmentToCard"){var data=request.content.action.data;var attachment_name=data.attachment.name;var attachment_url=data.attachment.url;var attachment_preview_url=data.attachment.previewUrl;message_text="New attachment added to card \"["+card_name+"](https://trello.com/c/"+card_link+")\"<br> **["+attachment_name+"]("+attachment_url+")**"}if(url==undefined||message_text==author_name)return;return{content:{alias:author_name,icon_url:user_avatar,"attachments":[{"color":"#FF0000","title":request.content.model.name,"title_link":request.content.model.shortUrl,"text":message_text+"<br>"+attachment_text}]}}};return Script}(); 
[34mI20171113-09:24:38.414(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error [Stack:] 
[34mI20171113-09:24:38.419(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error   TypeError: Cannot read property 'shortUrl' of undefined       at Script.process_incoming_request (script.js:1:420)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInNewContext (vm.js:18:15)       at Object.exports.runInNewContext (vm.js:49:17)       at Object.executeIntegrationRest [as action] (/app/bundle/programs/server/packages/rocketchat_integrations.js:2789:20)       at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:361:32)       at /app/bundle/programs/server/packages/nimble_restivus.js:250:33       at packages/simple_json-routes.js:98:9 
[34mI20171113-09:29:32.921(0)  
[34mI20171113-09:29:32.928(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error [Error running Script in Trigger Trello :] 
[34mI20171113-09:29:32.929(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error   function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}var Script=function(){function Script(){_classCallCheck(this,Script)}Script.prototype.process_incoming_request=function process_incoming_request(_ref){var request=_ref.request;console.log(request.content);var attachment_text="";var title_text="";var author_name=request.content.action.memberCreator.fullName;var card_name=request.content.action.data.card.name;var card_link=request.content.action.data.card.shortLink;var board_link=request.content.action.data.board.shortLink;var board_name=request.content.action.data.board.name;var user_avatar="https://trello-avatars.s3.amazonaws.com/"+request.content.action.memberCreator.avatarHash+"/170.png";var message_text=author_name;if(request.content.model.name=="Exergo")return"";if(request.content.action.type=="updateCheckItemStateOnCard"||request.content.action.type=="deleteCheckItem"||request.content.action.type=="createCheckItem"){if(request.content.action.type=="updateCheckItemStateOnCard"){if(request.content.action.data.checkItem.state=="incomplete")message_text+=" unchecked ";else message_text+=" checked ";message_text+=" a checklist item<br>"}else if(request.content.action.type=="deleteCheckItem"){message_text+=" deleted a checklist item"}else if(request.content.action.type=="createCheckItem"){message_text+=" created a checklist item"}title_text=card_name;attachment_text="<br>Item: "+request.content.action.data.checkItem.name;attachment_text+="<br>Checklist: "+request.content.action.data.checklist.name;attachment_text+="<br>Card: "+card_name}else if(request.content.action.type=="addChecklistToCard"){message_text+=" added a checklist to card";title_text=card_name;attachment_text+="<br>Checklist: "+request.content.action.data.checklist.name;attachment_text+="<br>Card: "+card_name}else if(request.content.action.type=="removeChecklistFromCard"){message_text+=" removed a checklist from card";title_text=card_name;attachment_text+="<br>Checklist: "+request.content.action.data.checklist.name;attachment_text+="<br>Card: "+card_name}else if(request.content.action.type=="createCard"){var list_name=request.content.action.data.list.name;message_text=" New card ["+card_name+"](https://trello.com/c/"+card_link+") added to list ["+list_name+"](https://trello.com/b/"+board_link+")";url="https://trello.com/c/"+request.content.action.data.card.shortLink;title_text=card_name}else if(request.content.action.type=="deleteCard"){var list_name=request.content.action.data.list.name;message_text="Card [#"+request.content.action.data.card.idShort+"](https://trello.com/c/"+card_link+") deleted from list ["+list_name+"](https://trello.com/b/"+board_link+")";url="https://trello.com/c/"+request.content.action.data.card.shortLink;title_text=""}else if(request.content.action.type=="updateCard"){var data=request.content.action.data;if(data.listBefore){message_text="Card moved: \"["+card_name+"](https://trello.com/c/"+card_link+")\" from list \""+data.listBefore.name+"' to '"+data.listAfter.name+"'"}else if(data.old.name){var card_old_name=data.old.name;message_text="Card renamed from \""+card_old_name+"\" to \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(data.old.desc!=data.card.desc){var card_desc=data.card.desc;var old_desc=data.old.desc;if(old_desc!=""){card_desc="from \""+old_desc+"\" to \""+card_desc+"\""}message_text="Card updated: \"["+card_name+"](https://trello.com/c/"+card_link+")\"<br>**Description**: "+card_desc+""}else if(data.card.due!=data.old.due){var card_due=data.card.due;var due_action=card_due;if(due_action==null)due_action="Removed";message_text="Card updated: \"["+card_name+"](https://trello.com/c/"+card_link+")\"<br>**Due Date**: "+due_action+""}else if(data.card.closed==true){message_text="Card archived: \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(data.card.closed==false){message_text="Card unarchived: \"["+card_name+"](https://trello.com/c/"+card_link+")\""}}else if(request.content.action.type=="commentCard"){var data=request.content.action.data;message_text="**New comment on card \"["+card_name+"](https://trello.com/c/"+card_link+")\" by "+author_name+"**";attachment_text+="-----------------------------------------------------------<br>"+data.text}else if(request.content.action.type=="moveCardFromBoard"){var data=request.content.action.data;var board_target_name=data.boardTarget.name;message_text="Card moved: \"["+card_name+"](https://trello.com/c/"+card_link+")\" moved from \"["+board_name+"](https://trello.com/b/"+board_link+") to board \""+board_target_name+"\""}else if(request.content.action.type=="moveCardToBoard"){var data=request.content.action.data;var board_source_name=data.boardSource.name;message_text="Card moved: \"["+card_name+"](https://trello.com/c/"+card_link+")\" moved to \"["+board_name+"](https://trello.com/b/"+board_link+") from board  \""+board_source_name+"\""}else if(request.content.action.type=="addMemberToCard"){var data=request.content.action.data;var member=request.content.action.member.fullName;var member_url=request.content.action.member.username;message_text="New member ["+member+"](https://trello.com/"+member_url+") added to card \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(request.content.action.type=="removeMemberFromCard"){var data=request.content.action.data;var member=request.content.action.member.fullName;var member_url=request.content.action.member.username;message_text="Member ["+member+"](https://trello.com/"+member_url+") is removed from card \"["+card_name+"](https://trello.com/c/"+card_link+")\""}else if(request.content.action.type=="addAttachmentToCard"){var data=request.content.action.data;var attachment_name=data.attachment.name;var attachment_url=data.attachment.url;var attachment_preview_url=data.attachment.previewUrl;message_text="New attachment added to card \"["+card_name+"](https://trello.com/c/"+card_link+")\"<br> **["+attachment_name+"]("+attachment_url+")**"}if(url==undefined||message_text==author_name)return;return{content:{alias:author_name,icon_url:user_avatar,"attachments":[{"color":"#FF0000","title":request.content.model.name,"text":message_text+"<br>"+attachment_text}]}}};return Script}(); 
[34mI20171113-09:29:32.933(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error [Stack:] 
[34mI20171113-09:29:32.935(0) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Incoming WebHook.error   TypeError: Cannot read property 'memberCreator' of undefined       at Script.process_incoming_request (script.js:1:429)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInNewContext (vm.js:18:15)       at Object.exports.runInNewContext (vm.js:49:17)       at Object.executeIntegrationRest [as action] (/app/bundle/programs/server/packages/rocketchat_integrations.js:2789:20)       at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:361:32)       at /app/bundle/programs/server/packages/nimble_restivus.js:250:33       at packages/simple_json-routes.js:98:9  `

**Comment by ktkd** [comment]
i found how fix this issue, first need add integration without js script because trello send first request (head) without any json data.
if i add integration and connect trello to it and then add js script all works fine. thanks.

**Comment by GezimSejdiu** [comment]
Hi @ktkd ,
right, it makes sense :) . I'm glad that you solved the issue and happy that you are using this integration for your RC instance.

Have fun with it and a lot of Trello tasks resolved  :).

Best regards,

**Comment by ktkd** [comment]
thank you so much too.

2017-11-13 16:05 GMT+03:00 Gezim Sejdiu <notifications@github.com>:

**Comment by anhhtca** [comment]
Hi,

Clear the script, run. Re-use script, run not resolve that error for me:
```
I20210603-00:50:31.449(0) server.js:204 Integrations ➔ Incoming WebHook.error [Stack:] 
I20210603-00:50:31.456(0) server.js:204 Integrations ➔ Incoming WebHook.error   Error: TypeError: Cannot read property 'shortUrl' of undefined       at evalmachine.<anonymous>:11:33       at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
```

Give me some ideas please !

Regards,
