### ISSUE TITLE
New Trello setup

### ISSUE THREAD

**Issue by HiveMindNet** [GezimSejdiu/Rocket.Chat-Trello-Integration#7]
Anyone please know how to make this work as Trello api setup looks to have changed. Thank you.

**Comment by GezimSejdiu** [comment]
Hi @HiveMindNet ,

indeed, it seems that the Trello API has changed, and will try to find sometime i.e. beginning of next month, and look into it how to fix it.

Many thanks for reporting the issue.

Best regards,

**Comment by HiveMindNet** [comment]
Thanks. We’ve moved to using Wekan now any which which is really cool. If you look at that at anytime and work a way to hook into that, please do let me know :)

**Comment by wolfcreative** [comment]
Hi @GezimSejdiu. Haven't you watched this task yet?

**Comment by GezimSejdiu** [comment]
Hey @wolfcreative ,

thanks a lot for the message. It was indeed in my TODOs but didn't manage to find some spare time to work on it. 

So, I just did manage to make it work with the new changes on the Trello API. Please, could you give it a try following the instructions on README and let me know in case of any issues.

Best regards,
